"""Add all models: users, templates, memes, behaviors, likes, shares, views, trend_predictions, notifications, sessions, reports

Revision ID: 759d07d1f598
Revises: d35b6d2eef8e
Create Date: 2026-04-28 10:39:21.167829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759d07d1f598'
down_revision: Union[str, None] = 'd35b6d2eef8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('caption_position', sa.String(length=20), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('text_color', sa.String(length=20), nullable=True),
    sa.Column('category_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('emotion_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_index(op.f('ix_templates_slug'), 'templates', ['slug'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('memes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('original_image_url', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('trending_score', sa.Float(), nullable=True),
    sa.Column('is_trending', sa.Boolean(), nullable=True),
    sa.Column('predicted_hot_at', sa.DateTime(), nullable=True),
    sa.Column('hot_prediction_probability', sa.Float(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memes_id'), 'memes', ['id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meme_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meme_id', name='unique_user_meme_like')
    )
    op.create_index(op.f('ix_likes_created_at'), 'likes', ['created_at'], unique=False)
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.create_index(op.f('ix_likes_meme_id'), 'likes', ['meme_id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.create_table('meme_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meme_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('view_duration', sa.Integer(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'meme_id', name='unique_user_meme_daily_view')
    )
    op.create_index(op.f('ix_meme_views_created_at'), 'meme_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_meme_views_id'), 'meme_views', ['id'], unique=False)
    op.create_index(op.f('ix_meme_views_meme_id'), 'meme_views', ['meme_id'], unique=False)
    op.create_index(op.f('ix_meme_views_user_id'), 'meme_views', ['user_id'], unique=False)
    op.create_table('reported_memes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meme_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meme_id', 'reporter_id', name='unique_user_meme_report')
    )
    op.create_index(op.f('ix_reported_memes_created_at'), 'reported_memes', ['created_at'], unique=False)
    op.create_index(op.f('ix_reported_memes_id'), 'reported_memes', ['id'], unique=False)
    op.create_index(op.f('ix_reported_memes_meme_id'), 'reported_memes', ['meme_id'], unique=False)
    op.create_index(op.f('ix_reported_memes_reporter_id'), 'reported_memes', ['reporter_id'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meme_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_created_at'), 'shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_shares_id'), 'shares', ['id'], unique=False)
    op.create_index(op.f('ix_shares_meme_id'), 'shares', ['meme_id'], unique=False)
    op.create_index(op.f('ix_shares_user_id'), 'shares', ['user_id'], unique=False)
    op.create_table('trend_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meme_id', sa.Integer(), nullable=False),
    sa.Column('likes_1h', sa.Integer(), nullable=True),
    sa.Column('views_1h', sa.Integer(), nullable=True),
    sa.Column('shares_1h', sa.Integer(), nullable=True),
    sa.Column('like_rate_1h', sa.Float(), nullable=True),
    sa.Column('share_rate_1h', sa.Float(), nullable=True),
    sa.Column('view_velocity', sa.Float(), nullable=True),
    sa.Column('hour_post', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('user_avg_likes', sa.Float(), nullable=True),
    sa.Column('hot_probability', sa.Float(), nullable=True),
    sa.Column('is_predicted_hot', sa.Boolean(), nullable=True),
    sa.Column('actually_hot', sa.Boolean(), nullable=True),
    sa.Column('actual_likes_24h', sa.Integer(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_predictions_id'), 'trend_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_trend_predictions_meme_id'), 'trend_predictions', ['meme_id'], unique=False)
    op.create_table('user_behaviors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meme_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('referrer_url', sa.String(length=500), nullable=True),
    sa.Column('time_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('week_of_year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meme_id'], ['memes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_behaviors_user_action_time', 'user_behaviors', ['user_id', 'action_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_behaviors_action_type'), 'user_behaviors', ['action_type'], unique=False)
    op.create_index(op.f('ix_user_behaviors_created_at'), 'user_behaviors', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_behaviors_id'), 'user_behaviors', ['id'], unique=False)
    op.create_index(op.f('ix_user_behaviors_user_id'), 'user_behaviors', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_behaviors_user_id'), table_name='user_behaviors')
    op.drop_index(op.f('ix_user_behaviors_id'), table_name='user_behaviors')
    op.drop_index(op.f('ix_user_behaviors_created_at'), table_name='user_behaviors')
    op.drop_index(op.f('ix_user_behaviors_action_type'), table_name='user_behaviors')
    op.drop_index('idx_behaviors_user_action_time', table_name='user_behaviors')
    op.drop_table('user_behaviors')
    op.drop_index(op.f('ix_trend_predictions_meme_id'), table_name='trend_predictions')
    op.drop_index(op.f('ix_trend_predictions_id'), table_name='trend_predictions')
    op.drop_table('trend_predictions')
    op.drop_index(op.f('ix_shares_user_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_meme_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_created_at'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_reported_memes_reporter_id'), table_name='reported_memes')
    op.drop_index(op.f('ix_reported_memes_meme_id'), table_name='reported_memes')
    op.drop_index(op.f('ix_reported_memes_id'), table_name='reported_memes')
    op.drop_index(op.f('ix_reported_memes_created_at'), table_name='reported_memes')
    op.drop_table('reported_memes')
    op.drop_index(op.f('ix_meme_views_user_id'), table_name='meme_views')
    op.drop_index(op.f('ix_meme_views_meme_id'), table_name='meme_views')
    op.drop_index(op.f('ix_meme_views_id'), table_name='meme_views')
    op.drop_index(op.f('ix_meme_views_created_at'), table_name='meme_views')
    op.drop_table('meme_views')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_meme_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_created_at'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_memes_id'), table_name='memes')
    op.drop_table('memes')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_templates_slug'), table_name='templates')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
