"""Fix timestamp

Revision ID: fb855382979c
Revises: 9ed3ee6c5be3
Create Date: 2026-04-28 17:30:21.223615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb855382979c'
down_revision: Union[str, None] = '9ed3ee6c5be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_behaviors', 'session_id')
    op.drop_column('user_behaviors', 'referrer_url')
    op.drop_column('user_behaviors', 'browser')
    op.drop_column('user_behaviors', 'device_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_behaviors', sa.Column('device_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('user_behaviors', sa.Column('browser', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user_behaviors', sa.Column('referrer_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('user_behaviors', sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
